export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:3000/api/';
export const ACCESS_TOKEN = 'accessToken';

export const LOW_LEVEL = 1;
export const MEDIUM_LEVEL = 2;
export const HIGH_LEVEL = 3; 

export const LOW_LEVEL_SUDDEN_BRAKIMG_GREEN = 6;
export const LOW_LEVEL_COLLISIONS_OF_HUMAN_GREEN = 8;
export const LOW_LEVEL_SPEED_OR_LANE_OR_COLLISIONS_OF_VEHICLE_GREEN =10;

export const LOW_LEVEL_SUDDEN_BRAKIMG_RED = 10;
export const LOW_LEVEL_COLLISIONS_OF_HUMAN_RED = 12;
export const LOW_LEVEL_SPEED_OR_LANE_OR_COLLISIONS_OF_VEHICLE_RED =20;



export const MEDIUM_LEVEL_SUDDEN_BRAKIMG_GREEN = 4;
export const MEDIUM_LEVEL_COLLISIONS_OF_HUMAN_GREEN = 6;
export const MEDIUM_LEVEL_SPEED_OR_LANE_OR_COLLISIONS_OF_VEHICLE_GREEN =8;


export const MEDIUM_LEVEL_SUDDEN_BRAKIMG_RED = 8;
export const MEDIUM_LEVEL_COLLISIONS_OF_HUMAN_RED = 10;
export const MEDIUM_LEVEL_SPEED_OR_LANE_OR_COLLISIONS_OF_VEHICLE_RED =14;


export const HIGH_LEVEL_SUDDEN_BRAKIMG_GREEN = 2;
export const HIGH_LEVEL_COLLISIONS_OF_HUMAN_GREEN = 8;
export const HIGH_LEVEL_SPEED_OR_LANE_OR_COLLISIONS_OF_VEHICLE_GREEN = 6;

export const HIGH_LEVEL_SUDDEN_BRAKIMG_RED = 5;
export const HIGH_LEVEL_COLLISIONS_OF_HUMAN_RED = 8;
export const HIGH_LEVEL_SPEED_OR_LANE_OR_COLLISIONS_OF_VEHICLE_RED =10;
